import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Navbar from "./components/Navbar";
import backgroundImage from "../public/design-space-paper-textured-background.jpg";
import "./globals.css";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        backgroundImage: `url(${backgroundImage.src})`,
      }}
    >
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
